name: Code Quality Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pmd:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Quality check
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
      - uses: pmd/pmd-github-action@v2.0.0
        id : pmd
        with:
          sourcePath: 'app/src/main/java'
          rulesets: 'category/java/errorprone.xml'
      - name: Fail build if there are violations
        if: steps.pmd.outputs.violations != 0
        run: exit 1
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: pmd-report.sarif
